FROM ubuntu:17.04
MAINTAINER juliandondero@gmail.com

RUN useradd -ms /bin/bash user
USER user
WORKDIR /home/user
ENV NODE_VERSION 8.4.0

USER root

# supervisord from ubuntu repository
RUN apt-get update && apt-get install -y supervisor
RUN apt-get install -y apt-utils
RUN apt-get install -y git-core
RUN apt-get install -y ca-certificates
RUN apt-get install -y ssh
RUN apt-get install -y curl
RUN apt-get install -y vim
RUN apt-get install -y automake
RUN apt-get install -y autoconf
RUN apt-get install -y build-essential
RUN apt-get install -y python-dev
RUN apt-get install -y software-properties-common

COPY ./scripts/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
	
ADD ssh/ /home/user/.ssh/
RUN chmod 600 /home/user/.ssh/*
RUN ssh-keyscan github.com > /home/user/.ssh/known_hosts
RUN chown user:user /home/user/.ssh/*

USER user
WORKDIR /home/user

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash \ 
	&& /bin/bash -c "source ~/.bashrc && source /home/user/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION && nvm use default && npm install npm@latest -g && npm install bower -g && npm install -g yarn && npm install sails -g && npm install express -g"

USER root

# --- Download Android SDK tools

# RUN useradd -u 1000 -M -s /bin/bash user
RUN chown 1000 /opt

USER root

CMD ["/usr/bin/supervisord"]
